<?php
declare(strict_types=1);

namespace TeBo\Command;

use Cake\Command\Command;
use Cake\Console\Arguments;
use Cake\Console\ConsoleIo;
use Cake\Console\ConsoleOptionParser;
use TeBo\Enum\TelegramMethod;
use TeBo\Service\ApiService;
use TeBo\Utility\Bot;

/**
 * TeboWebhook command.
 */
class TeboWebhookCommand extends Command
{
    use FormatPrintTrait;

    /**
     * @inheritDoc
     */
    public static function defaultName(): string
    {
        return 'tebo webhook';
    }

    /**
     * Implement this method with your command's logic.
     *
     * @param \Cake\Console\Arguments $args The command arguments.
     * @param \Cake\Console\ConsoleIo $io The console io
     * @return null|void|int The exit code or null for success
     */
    public function execute(Arguments $args, ConsoleIo $io)
    {
        $apiService = new ApiService();

        if ($args->getOption('set')) {
            $io->comment('Setting webhook:');
            $url = $args->getOption('url');
            if (empty($url)) {
                $url = Bot::getWebhookUrl();
            }
            $this->formatPrint($apiService->call(TelegramMethod::SET_WEBHOOK, ['url' => $url]), $io);
        } elseif ($args->getOption('delete')) {
            $io->comment('Deleting webhook:');
            $this->formatPrint($apiService->call(TelegramMethod::DELETE_WEBHOOK), $io);
        } elseif ($args->getOption('info')) {
            $io->comment('Getting webhook info:');
            $this->formatPrint($apiService->call(TelegramMethod::GET_WEBHOOK_INFO), $io);
        } elseif ($args->getOption('bot-info')) {
            $io->comment('Getting bot info (getMe):');
            $this->formatPrint($apiService->call(TelegramMethod::GET_ME), $io);
        } elseif ($args->getOption('default-url')) {
            $io->comment('Getting default webhook URL:');
            $url = Bot::getWebhookUrl();
            $io->out('Default generated webhook URL:');
            $io->out('<info>' . $url . '</info>');
        } else {
            $io->out($this->getOptionParser()->help());
        }

        return static::CODE_SUCCESS;
    }

    /**
     * Hook method for defining this command's option parser.
     *
     * @see https://book.cakephp.org/4/en/console-commands/commands.html#defining-arguments-and-options
     * @param \Cake\Console\ConsoleOptionParser $parser The parser to be defined
     * @return \Cake\Console\ConsoleOptionParser The built parser.
     */
    public function buildOptionParser(ConsoleOptionParser $parser): ConsoleOptionParser
    {
        $parser = parent::buildOptionParser($parser);

        $parser->setDescription(
            'Manages the Telegram Bot Webhook.'
        );

        $parser->addOptions([
            'set' => [
                'short' => 's',
                'help' => 'Set or register the webhook URL with Telegram.',
                'boolean' => true,
            ],
            'delete' => [
                'short' => 'd',
                'help' => 'Remove the current webhook integration from Telegram.',
                'boolean' => true,
            ],
            'info' => [
                'short' => 'i',
                'help' => 'Get the current webhook status and information.',
                'boolean' => true,
            ],
            'bot-info' => [
                'short' => 'b',
                'help' => 'Get the bot\'s basic info (API getMe).',
                'boolean' => true,
            ],
            'default-url' => [
                'short' => 'g',
                'help' => 'Show the default generated webhook URL.',
                'boolean' => true,
            ],
            'url' => [
                'short' => 'u',
                'help' => 'A custom URL to use with --set. If omitted, the default generated URL is used.'
            ]
        ]);

        $parser->setEpilog([
            '<info>Usage Examples:</info>',
            '',
            '  <comment>Set the webhook with the default URL (generated by Bot::getWebhookUrl()):</comment>',
            '  bin/cake tebo webhook --set',
            '',
            '  <comment>Show the default generated URL (without setting it):</comment>',
            '  bin/cake tebo webhook --default-url',
            '',
            '  <comment>Set the webhook with a specific manual URL:</comment>',
            '  bin/cake tebo webhook --set --url https://my.domain.com/webhook',
            '',
            '  <comment>Check the current webhook status:</comment>',
            '  bin/cake tebo webhook --info',
            '',
            '  <comment>Remove the webhook:</comment>',
            '  bin/cake tebo webhook --delete',
            '',
            '  <comment>Get the bot\'s info:</comment>',
            '  bin/cake tebo webhook --bot-info',
        ]);

        return $parser;
    }
}
